name: Build Windows EXE (No External Actions)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo and Build EXE
      run: |
        # Clone repo manually since we can't use actions/checkout
        git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY repo
        cd repo

        # Download and extract latest llvm-mingw toolchain
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20250417/llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        tar -xf llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        mv llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64 llvm-mingw
        export PATH="$PWD/llvm-mingw/bin:$PATH"

        # Build the EXE
        x86_64-w64-windows-gnu-clang vbmeta-disable-verify.c -o vbmeta-disable-verify.exe

        # Confirm output
        ls -lh vbmeta-disable-verify.exe
