name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3d9f75e540eb420dd2b927fa6d527a7c9d1cfa3a # checkout@v3.5.3

    - name: Download llvm-mingw (20250417)
      run: |
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20250417/llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        tar -xf llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        mv llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64 llvm-mingw
        echo "$GITHUB_WORKSPACE/llvm-mingw/bin" >> $GITHUB_PATH

    - name: Build Windows EXE
      run: |
        x86_64-w64-windows-gnu-clang vbmeta-disable-verify.c -o vbmeta-disable-verify.exe

    - name: Upload EXE
      uses: actions/upload-artifact@3dbf6c67f5c7c04c513fa1b3ff7171ef60ae9d80 # upload-artifact@v3.1.3
      with:
        name: vbmeta-disable-verify
        path: vbmeta-disable-verify.exe
