name: Build Windows EXE (No Actions)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone, Install Toolchain, and Build
      run: |
        # Clone source manually
        git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" repo
        cd repo

        # Download and extract llvm-mingw
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20250417/llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        tar -xf llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz

        # Move and prepare path
        mv llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64 llvm-mingw
        export TOOLCHAIN_DIR="$PWD/llvm-mingw/bin"
        export PATH="$TOOLCHAIN_DIR:$PATH"

        # Debug: check compiler exists
        ls -l "$TOOLCHAIN_DIR/x86_64-w64-windows-gnu-clang"
        which x86_64-w64-windows-gnu-clang

        # Build the executable
        x86_64-w64-windows-gnu-clang vbmeta-disable-verify.c -o vbmeta-disable-verify.exe

        # Confirm output
        ls -lh vbmeta-disable-verify.exe
