name: Build Windows EXE (No Actions Used)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      run: |
        git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY repo
        cd repo
        cp vbmeta-disable-verify.c ../
        cd ..

    - name: Download llvm-mingw
      run: |
        wget https://github.com/mstorsjo/llvm-mingw/releases/download/20250417/llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        tar -xf llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64.tar.xz
        mv llvm-mingw-20250417-ucrt-ubuntu-22.04-x86_64 llvm-mingw
        echo "$GITHUB_WORKSPACE/llvm-mingw/bin" >> $GITHUB_PATH

    - name: Build Windows EXE
      run: |
        x86_64-w64-windows-gnu-clang vbmeta-disable-verify.c -o vbmeta-disable-verify.exe

    - name: Display Build Result
      run: ls -lh vbmeta-disable-verify.exe
